### ISSUE TITLE
Switch to numpy array

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/sot-core#127]
I believe all the Python code is not compatible with numpy arrays. In particular, the file matrix_utils.py.

**Comment by nim65s** [comment]
Ok so we have an implementation of `RPYToMatrix` in C++ and another in python. ref #128 

I implemented a few dumb tests in matrix_utils.py, and saw no issue between np.array and np.matrix. In this file, we mostly work with python lists / tuples, instead of np.array / np.matrix.

Did I miss anything ?

**Comment by jmirabel** [comment]
I don't remember where I had issues then. I let you move on if everything works from your side.

Just, before merging and releasing, check that no-one needs the binaries on the robot. There is the IROS deadline in a few days so it may be better to wait until it is passed.

**Comment by nim65s** [comment]
Merging and releasing what ?

Eigenpy v2 is already in robotpkg binaries, and my [patch](https://github.com/nim65s/robotpkg-wip/blob/master/py-sot-talos/patches/patch-aa) for sot-talos too. 
Plus @olivier-stasse just pushed a release of sot-core on robotpkg.

**Comment by olivier-stasse** [comment]
private discussion with @jmirabel seems to show that IROS submission will not be directly impacted. Unless somebody else is complaining.

**Comment by nim65s** [comment]
Then I think we can close this.
